[package]
name = "aoc-14-2016"
version = "0.1.0"
authors = ["Sameer Kolhar <kolhar730@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"